export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "Lena Johnson",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpeg",
        username: "Oliver Smith",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Harper Davis",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpeg",
        username: "Ethan Brown",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Isla Wilson",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "James Green",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Ava Martinez",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpeg",
        username: "Lucas Taylor",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpeg",
        username: "Emily Moore",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.jpeg",
        username: "Mason Lee",
    },
];


export const Posts = [
    {
        id: 1,
        desc: "Adventure awaits, go find it.",
        photo: "assets/post/15.jpg",
        date: "10 mins ago",
        userId: 1,
        like: 24,
        comment: 4,
    },
    {
        id: 2,
        desc: "Happiness is a journey, not a destination.",
        photo: "assets/post/14.jpg",
        date: "30 mins ago",
        userId: 2,
        like: 19,
        comment: 2,
    },
    {
        id: 3,
        desc: "Just living my best life!",
        photo: "assets/post/13.jpg",
        date: "45 mins ago",
        userId: 3,
        like: 85,
        comment: 6,
    },
    {
        id: 4,
        desc: "The best is yet to come.",
        photo: "assets/post/12.jpg",
        date: "1 hour ago",
        userId: 4,
        like: 33,
        comment: 3,
    },
    {
        id: 5,
        desc: "Do more of what makes you happy.",
        photo: "assets/post/11.jpg",
        date: "3 hours ago",
        userId: 5,
        like: 57,
        comment: 5,
    },
    {
        id: 6,
        desc: "Smile and the world smiles with you.",
        photo: "assets/post/6.jpeg",
        date: "6 hours ago",
        userId: 6,
        like: 67,
        comment: 10,
    },
    {
        id: 7,
        desc: "Life is short, make it sweet.",
        photo: "assets/post/7.jpeg",
        date: "1 day ago",
        userId: 7,
        like: 92,
        comment: 8,
    },
    {
        id: 8,
        desc: "Dream big, work hard, stay focused.",
        photo: "assets/post/8.jpeg",
        date: "2 days ago",
        userId: 8,
        like: 43,
        comment: 1,
    },
    {
        id: 9,
        desc: "Be yourself, everyone else is taken.",
        photo: "assets/post/9.jpeg",
        date: "4 days ago",
        userId: 9,
        like: 29,
        comment: 2,
    },
    {
        id: 10,
        desc: "You only live once, but if you do it right, once is enough.",
        photo: "assets/post/10.jpeg",
        date: "1 week ago",
        userId: 10,
        like: 128,
        comment: 14,
    },
];
